version: 25
jobs:
- name: Push to GitHub
  steps:
  - !PushRepository
    name: push
    remoteUrl: https://github.com/VMGWARE/js-validator
    passwordSecret: access-token
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  - !TagCreateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
