version: 25
jobs:
- name: Build
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: build & test
    runInContainer: true
    image: node:18
    interpreter: !DefaultInterpreter
      commands:
      - npm ci
      - export CI=TRUE
      - npm run lint
      - npm test -- --json --outputFile=testResults.json
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishJestReportStep
    name: publish test report
    reportName: Jest Test Report
    filePatterns: testResults.json
    condition: ALWAYS
  triggers:
  - !BranchUpdateTrigger {}
  - !PullRequestUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Deploy
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: publish
    runInContainer: true
    image: node:18
    interpreter: !DefaultInterpreter
      commands:
      - npm ci
      - npm run build
      - echo //registry.npmjs.org/:_authToken=@secret:NODE_AUTH_TOKEN@ >> .npmrc
      - echo email=@secret:NODE_AUTH_EMAIL@ >> .npmrc
      - echo always-auth=true >> .npmrc
      - npm publish --access public
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !TagCreateTrigger {}
  jobDependencies:
  - jobName: Build
    requireSuccessful: true
    artifacts: '**'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Sync Main (GitHub)
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: sync
    runInContainer: true
    image: alpine/git:1.0.7
    interpreter: !DefaultInterpreter
      commands:
      - git config --global --unset http.extraHeader
      - git push -f https://codycody31:@secrets:access-token@@@github.com/VMGWARE/js-validator.git HEAD:main
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: main
    projects: js-validator
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
