# .github/workflows/test-and-build.yml

name: Test & Build

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    container: node:18

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Lint and Test
        run: |
          export CI=TRUE
          npm run lint:ci
          npm test -- --coverage --json --outputFile=testResults.json
